### ISSUE TITLE
Add support for transit gateway

### ISSUE THREAD

**Issue by hniemann** [terraform-aws-modules/terraform-aws-vpn-gateway#21]
Can you please add support for transit gateway?

Thanks for this great module!

**Comment by miguelaferreira** [comment]
I'm happy that you find the module useful @hniemann.
I cannot make commitments to the timeline but I'll try to get an initial implementation working with transit gateway. I think this will also involve adding transit gateways to the vpc module.

Feel free to give it a start, otherwise I'll update this issue which what I'm doing.

**Comment by miguelaferreira** [comment]
@hniemann There is an open #PR26 that adds support for transit gateways. I'm currently testing it. Would you be able to also test it in your own use cases?

**Comment by antonbabenko** [comment]
@hniemann [v2.4.0](https://github.com/terraform-aws-modules/terraform-aws-vpn-gateway/releases/v2.4.0) has this feature available. See examples for more details.
