### ISSUE TITLE
Importing unrelated resource causes an Error

### ISSUE THREAD

**Issue by hhh0505** [terraform-aws-modules/terraform-aws-vpn-gateway#30]
I have this module being called 4 times to create different vpn connections with VPC ID, VGW and CGW being pased to the module.

When I try to import a resource, while it's preparing it throws the following error:

```
Error: Invalid template interpolation value

  on .terraform/modules/vpn-connection/terraform-aws-modules-terraform-aws-vpn-gateway-051039a/main.tf line 13, in locals:
  13:   connection_identifier = var.connect_to_transit_gateway ? "TGW ${var.transit_gateway_id}" : "VPC ${var.vpc_id}"
    |----------------
    | var.vpc_id is null

The expression result is null. It cannot include a null value in a string
template.
```

Only way around this for now is having to comment out the VPN module and import.

**Comment by John-OShea-Wordbank** [comment]
Confirming the same issue, and that the workaround (commenting out just the VPN module definitions) works - `terraform plan` shows no errors.

**Comment by antonbabenko** [comment]
Importing resources is usually tricky when working to import a complex resource that is created conditionally inside of a module.

In order to make a better fix, I need to triage this and spend more time.

Closing this issue, because the solution provided by @John-OShea-Wordbank should be working. If not, please provide the terraform code snippet you have.
