### ISSUE TITLE
Support static Tunnel CIDR in module

### ISSUE THREAD

**Issue by bequiet88** [terraform-aws-modules/terraform-aws-vpn-gateway#6]
Hey,
First of all, thanks for this great module. Appreciate it!

Can you please support the following parameters of TF resource aws_vpn_connection:
tunnel1_inside_cidr - (Optional) The CIDR block of the inside IP addresses for the first VPN tunnel.
tunnel2_inside_cidr - (Optional) The CIDR block of the second IP addresses for the first VPN tunnel.
tunnel1_preshared_key - (Optional) The preshared key of the first VPN tunnel.
tunnel2_preshared_key - (Optional) The preshared key of the second VPN tunnel. 

They have been added in TF 0.11.3 and AWS module 1.8.0 - if you are too busy, I can open a Pull Request as well. Just let me know.

Thanks and cheers,
Jochen

**Comment by antonbabenko** [comment]
Yes, please open a PR. I hope @miguelaferreira can take a look at it also.

**Comment by miguelaferreira** [comment]
I will definitely take the time to help with a PR

**Comment by levequej** [comment]
Hi,
I've had a look at @bequiet88  fork : looks perfect, but it would also be nice to have the possibility to output (to enable with a conditional maybe)  pre shared keys.
I know we need this (retrieved from encrypted s3 backend remote state) in order to automate the VPN creation for configuring the on-prem VPN appliance :)

**Comment by miguelaferreira** [comment]
I've also looked at the fork of @bequiet88 and I'm left wondering if that is ready for a PR to this repo?

@levequej AFAIK, I don't think you can make an output conditional on something. Also I would expect that you can get the keys from the remote state in S3 without outputting it from this module. Then once you retrieved the keys from another another terraform configuration you could safely output it to a file or something like that.

**Comment by antonbabenko** [comment]
@bequiet88 You can write something like this:
```
value = "${element(concat(aws_vpn_connection.default.*.id, aws_vpn_connection.tunnel.*.id, aws_vpn_connection.preshared.*.id, aws_vpn_connection.tunnel_preshared.*.id, list("")), 0)}"
```

**Comment by dbadrak** [comment]
Hi. This looks right in the output (vpn_connection_id), but it doesn't get applied static route setup. I have the preshared key configuration, and got this:

* module.vpn_gateway.aws_vpn_connection_route.default[0]: 1 error(s) occurred:

* aws_vpn_connection_route.default.0: Error creating VPN connection route: MissingParameter: The request must contain the parameter vpnConnectionId
        status code: 400, request id: 8ea591e2-a9fb-43db-a882-7e9447dee4c7

in main.tf:

```
resource "aws_vpn_connection_route" "default" {
  count = "${var.create_vpn_connection ? (var.vpn_connection_static_routes_only ? length(var.vpn_connection_static_routes_destinations) : 0) : 0}"

  vpn_connection_id      = "${element(split(",", (var.create_vpn_connection ? join(",", aws_vpn_connection.default.*.id) : "")), 0)}"
  destination_cidr_block = "${element(var.vpn_connection_static_routes_destinations, count.index)}"
}
```

The problem here appears to be the vpn_connection_id is assumed to be just from the default, not from the other types (tunnel, tunnel_preshared, preshared).

**Comment by dbadrak** [comment]
@miguelaferreira  My config looks like

```
module "vpn_gateway" {
  source = "terraform-aws-modules/vpn-gateway/aws"

  vpc_id                  = "${module.vpc.vpc_id}"
  vpn_gateway_id          = "${module.vpc.vgw_id}"
  customer_gateway_id     = "${aws_customer_gateway.main.id}"
  vpn_connection_static_routes_only = true

  tunnel1_preshared_key = "${var.vpn_preshared_key}"
  tunnel2_preshared_key = "${var.vpn_preshared_key}"
}
```

This gets the preshared configuration from main.tf

```
resource "aws_vpn_connection" "preshared" {
  count = "${var.create_vpn_connection && length(var.tunnel1_inside_cidr) == 0  && length(var.tunnel2_inside_cidr) == 0 && length(var.tunnel1_preshared_key) > 0 && length(var.tunnel2_preshared_key) > 0 ? 1 : 0}"
```

The config generated is from '```terraform show``` starts like

```
module.vpn_gateway.aws_vpn_connection.preshared:
  id = vpn-xxxxxx
```

So, the id I believe it needs to be looking for is ```module.vpn_gateway.preshared.id```.
