### ISSUE TITLE
Add create_before_destroy for Customer Gateway resources

### ISSUE THREAD

**Issue by kai-66degrees** [terraform-aws-modules/terraform-aws-vpn-gateway#69]
## Description

When you try to change the IP for a customer gateway resource, following error is encountered:

Error: error deleting EC2 Customer Gateway (cgw-abcde): IncorrectState: The customer gateway is in use. status code: 400, request id: 1234xyz

I think adding a create_before_destroy to the customer gateway resource should fix it.

**Comment by pmckl** [comment]
Since the `aws_customer_gateway` resource creation is happening outside of this module, you can do it easily. 
But i agree it would make sense to extend the examples with the lifecycle attribute, and a comment why it's necessary.

i've changed one of the examples with the following, and worked as expected:

```tf
resource "aws_customer_gateway" "main" {
  bgp_asn    = 65000
  ip_address = "172.83.124.15"
  type       = "ipsec.1"

  tags = {
    Name = "complete-vpn-gateway"
  }
  lifecycle {
    create_before_destroy = true
  }
}
```
